'use strict';

var RB = require('react-bootstrap');
var FilteredList = require('./FilteredList/FilteredList').default;
var Spinner = require('./Spinner/Spinner').default;
var TwitterFeed = require('./TwitterFeed/TwitterFeed').default;
var FilteredTable = require('./FilteredTable/FilteredTable').default;
var PasswordValidator = require('./PasswordValidator/PasswordValidator').default;
require('./i18n/i18n.js');

module.exports = {
    FilteredList: FilteredList,
    Spinner: Spinner,
    TwitterFeed: TwitterFeed,
    FilteredTable: FilteredTable,
    PasswordValidator: PasswordValidator,
    // React Bootstrap
    Accordion: RB.Accordion,
    Alert: RB.Alert,
    Badge: RB.Badge,
    Breadcrumb: RB.Breadcrumb,
    BreadcrumbItem: RB.BreadcrumbItem,
    Button: RB.Button,
    ButtonGroup: RB.ButtonGroup,
    ButtonToolbar: RB.ButtonToolbar,
    Carousel: RB.Carousel,
    CarouselItem: RB.CarouselItem,
    Checkbox: RB.Checkbox,
    Clearfix: RB.Clearfix,
    ControlLabel: RB.ControlLabel,
    Col: RB.Col,
    Collapse: RB.Collapse,
    Dropdown: RB.Dropdown,
    DropdownButton: RB.DropdownButton,
    Fade: RB.Fade,
    Form: RB.Form,
    FormControl: RB.FormControl,
    FormGroup: RB.FormGroup,
    Glyphicon: RB.Glyphicon,
    Grid: RB.Grid,
    HelpBlock: RB.HelpBlock,
    Image: RB.Image,
    InputGroup: RB.InputGroup,
    Jumbotron: RB.Jumbotron,
    Label: RB.Label,
    ListGroup: RB.ListGroup,
    ListGroupItem: RB.ListGroupItem,
    Media: RB.Media,
    MenuItem: RB.MenuItem,
    Modal: RB.Modal,
    ModalBody: RB.ModalBody,
    ModalFooter: RB.ModalFooter,
    ModalHeader: RB.ModalHeader,
    ModalTitle: RB.ModalTitle,
    Nav: RB.Nav,
    Navbar: RB.Navbar,
    NavbarBrand: RB.NavbarBrand,
    NavDropdown: RB.NavDropdown,
    NavItem: RB.NavItem,
    Overlay: RB.Overlay,
    OverlayTrigger: RB.OverlayTrigger,
    PageHeader: RB.PageHeader,
    PageItem: RB.PageItem,
    Pager: RB.Pager,
    Pagination: RB.Pagination,
    Panel: RB.Panel,
    PanelGroup: RB.PanelGroup,
    Popover: RB.Popover,
    ProgressBar: RB.ProgressBar,
    Radio: RB.Radio,
    ResponsiveEmbed: RB.ResponsiveEmbed,
    Row: RB.Row,
    SafeAnchor: RB.SafeAnchor,
    SplitButton: RB.SplitButton,
    Tab: RB.Tab,
    TabContainer: RB.TabContainer,
    TabContent: RB.TabContent,
    Table: RB.Table,
    TabPane: RB.TabPane,
    Tabs: RB.Tabs,
    Thumbnail: RB.Thumbnail,
    Tooltip: RB.Tooltip,
    Well: RB.Well
};